Perfume E-Commerce Market Analysis

In [10]:
#Import important libraries

import pandas as pd

In [11]:
# Load the dataset for men's and women's perfumes
mens_perfume_df = pd.read_csv('ebay_mens_perfume.csv')
womens_perfume_df = pd.read_csv('ebay_womens_perfume.csv')

In [12]:
#Look at data 
mens_perfume_df.head(5)

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"

In [13]:
#Look at data 
womens_perfume_df.head(5)

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Carolina Herrera,Good Girl by Carolina Herrera 2.7 oz Eau De Pa...,Eau de Parfum,43.99,US $43.99/ea,2.0,2 available / 393 sold,393.0,"May 23, 2024 10:43:50 PDT","Thomasville, Alabama, United States"
1,As Shown,Parfums de Marly Delina La Rosee Eau de Parfum...,Eau de Parfum,79.99,US $79.99,5.0,5 available / 40 sold,40.0,"May 24, 2024 00:15:48 PDT","New Jersey, Hong Kong"
2,PRADA,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,US $59.99,10.0,More than 10 available / 35 sold,35.0,"May 14, 2024 20:54:25 PDT","Orange, New Jersey, United States"
3,As Show,J'adore Parfum D'eau by Christian 3.4 oz EDP F...,Eau de Parfum,59.99,US $59.99/ea,10.0,More than 10 available / 9 sold,9.0,"May 23, 2024 01:23:05 PDT","USA, New Jersey, Hong Kong"
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,US $29.99/ea,10.0,More than 10 available,NaN,NaN,"Little Ferry, New Jersey, United States"

In [26]:
#Count occurances of different brands in women parfumes 
counts = {}

for value in womens_perfume_df['brand']:
    counts[value] = counts.get(value, 0) + 1

print(counts)
print(counts['Versace'])

{'Carolina Herrera': 27, 'As Shown': 2, 'PRADA': 11, 'As Show': 12, 'Khadlaj': 3, 'Viktor & Rolf': 10, 'AS SHOW': 3, 'Versace': 33, 'Lattafa': 12, 'Yves Saint Laurent': 25, 'Gucci': 16, 'Coach': 15, 'Guerlain': 2, 'Philosophy': 6, 'Marc Jacobs': 14, 'AS SHOWN': 15, 'Dolce & Gabbana': 13, 'QRC': 1, '~ CREPE ERASE ~': 1, 'Unbranded': 11, 'YSL': 2, 'Parfums de Marly': 19, 'Dolce&Gabbana': 30, 'EX NIHILO': 1, 'Juliette has a gun': 10, 'Davidoff': 4, 'Giorgi^o Armani': 2, 'Roja': 1, 'Ariana Grande': 25, 'Sol De Janeiro': 5, 'Kilian': 12, 'Donna Karan': 9, 'Narciso Rodriguez': 9, 'Giorgio² Armani': 3, 'KENZO': 2, 'Burberry': 21, 'Thierry Mugler': 18, 'Juicy Couture': 13, 'Maison Margiela': 4, 'Jo Malone': 29, 'Elizabeth Arden': 12, 'Urban Outfitters': 1, 'Dossier': 13, 'Maison Alhambra': 9, 'ALT Fragrances': 2, 'Estée Lauder': 12, "Victoria's Secret": 26, 'Kim Kardashian': 3, 'Gap': 2, 'Cacharel': 6, 'Jessica McClintock': 2, 'AS  SHOWN': 1, 'Clinique': 11, 'Valentino': 11, 'Giorgio Armani': 12, 'Jimmy Choo': 13, 'Calvin Klein': 17, 'Alfred Sung': 1, 'Gloria Vanderbilt': 1, 'Parfums': 1, 'Ouai': 4, 'Lancôme': 37, 'Ellis Brooklyn': 3, 'Elizabeth Taylor': 7, 'Generic': 1, 'Al Haramain': 2, 'Al Rehab': 2, 'BYREDO': 1, 'Huda Beauty Kayali': 1, 'Evyan': 2, 'Lake&skye': 1, 'Frederic Malle': 1, 'Marilyn Miglin': 1, 'Aquolina': 2, 'Perry Ellis': 3, 'Armaf': 8, 'Lattafa Perfumes': 1, 'ALFRED SUNG': 4, 'Katy Perry': 2, 'Montblanc': 2, 'Atelier Cologne': 1, 'Christian Audigier': 3, 'Vera Wang': 3, 'GUESS': 3, 'Coty': 1, 'Clean': 3, 'Afnan': 3, 'Britney Spears': 8, 'Estee Lauder': 1, 'Givenchy': 13, 'ESCADA': 3, 'Michael Kors': 6, 'Le Labo': 3, 'Hollister': 2, 'Ralph Lauren': 9, 'Glossier': 1, 'Dolce Gabbana': 1, 'Chloe': 1, 'LANCOME': 1, 'Lancome': 3, 'Natalie': 1, 'Paris Hilton': 4, 'Avon': 7, 'Chaka by Chaka Khan': 1, 'CHANEL': 9, 'HUGO BOSS': 3, 'Huda Beauty': 1, 'Bellie Eilish': 1, 'Lucky': 1, 'Giorgio Beverly Hills': 1, 'TF': 1, 'Juliette Has a Gun': 1, 'Oscar de la Renta': 4, 'Elizabeth And James Nirvana': 1, 'FLOWER': 2, 'Tom Ford': 4, 'Lanvin': 5, 'Parfums Gres': 1, 'Vicki Tiel': 1, 'Moschino': 4, 'Dior': 4, 'Fragonard': 4, 'Kate Spade New York': 1, 'Spiritual Sky': 1, 'al hambra': 1, 'GIORGIO BEVERLY HILLS': 1, 'J. Del Pozo': 2, 'True Religion': 1, 'Taylor Swift': 2, 'HERMÈS': 7, 'Paco Rabanne': 2, 'Kenneth Cole': 1, 'Creed': 4, 'Byredo': 1, 'Acqua di Parma': 2, 'Dana': 3, 'Liz Claiborne': 4, 'M·A·C': 2, 'Robert Piguet': 4, 'Halston': 1, 'Gloss Moderne': 1, 'Justin Bieber': 1, 'Revlon': 1, 'Sarah Jessica Parker': 3, 'Jennifer Lopez': 2, 'Xerjoff': 1, 'Kate Spade': 3, 'Gianni Versace': 3, 'Zara': 2, 'Al Wataniah': 2, 'J Lo': 1, 'Yardley London': 2, 'Pure Romance': 1, 'Tous': 1, "Perfumer's Workshop": 1, 'Boucheron': 1, 'Parfum': 1, 'Sean John': 1, 'Bvlgari': 4, 'Adam Levine': 1, 'Jean couturier': 1, 'Chopard': 1, 'CHANGE For Women': 1, 'ASST': 1, 'Al-Rehab': 1, 'Tiziana Terenzi': 1, 'Tory Burch': 1, 'Miraclelayer': 1, 'Fragrance Couture': 1, 'One Direction': 2, 'Mancera': 3, 'Montale': 2, 'Prince Matchabelli': 1, 'Giardini Di Toscana': 1, 'Assorted': 1, 'Jessica Simpson': 3, 'love luxe beauty': 1, 'Tru Fragrance': 1, 'Sabrina Carpenter': 1, 'Nest': 1, 'Parfums Grès': 1, 'Multiple Brands': 1, 'Designer Series': 1, 'Paloma Picasso': 1, 'As Picture Show': 1, 'Aeropostale': 1, 'PHLUR': 1, 'JLO': 1, 'Ainash Perfums': 1, 'Salvatore Ferragamo': 3, 'diptyque': 1, 'as showed': 1, 'Maison Martin Margiela': 1, 'T.O.V.A.': 2, 'Jovan': 2, 'Benetton': 1, 'Tiffany & Co.': 1, 'Fred Hayman': 1, 'Miim Miic': 1, 'Escada': 3, 'AERIN': 2, 'Giorgio Arm.ani': 1, 'Pleasing': 1, 'PINK': 1, 'Perfume': 1, 'ULTA': 1, 'Rihanna': 1, 'Vilhelm Parfumerie': 1, 'Preferred Fragrance': 1, 'Sisley': 1, 'Anna Sui': 2, 'Fuller Armand Dupree': 1, 'dossier': 1, 'BURBERRY': 1, 'Atlantic': 1, "L'Artisan": 1, 'Clubman Pinaud': 1, 'Lomani': 1, 'Tommy Hilfiger': 1, 'Banana Republic': 1, 'Lolita Lempicka': 1, 'MONTALE': 1, 'ISSEY MIYAKE': 2, nan: 1, 'Baby Phat': 1, 'MEM': 1, 'Gwen Stefani': 2, 'Chloé': 1, 'Jeanne Arthes': 1, 'Jean Paul Gaultier': 1, 'Daddy Yankee': 1, 'Classic Erotica': 1, 'Pacifica': 1, 'Snif': 1, 'Bath & Body Works': 2, 'Rasasi': 1, 'The Body Shop': 1, 'Five Star Fragrance': 1, 'Pink sugar': 1, 'Elizabeth & James': 1, 'Elie Saab': 1, 'SEE PHOTO': 1, 'Armand Dupree Fuller': 1, 'DKNY': 1, 'United Colors of Benetton': 1, 'Maison': 1, 'Vince Camuto': 1, 'Juliette Has A Gun': 1}
33

In [27]:
#Count occurances of different brands in women parfumes 
counts = {}

for value in mens_perfume_df['brand']:
    counts[value] = counts.get(value, 0) + 1

print(counts)
print(counts['Versace'])

{'Dior': 11, 'AS SHOW': 7, 'Unbranded': 39, 'Giorgio Armani': 60, 'Lattafa': 13, 'Multiple Brands': 1, 'Maison Alhambra': 4, 'Gucci': 9, 'Ralph Lauren': 41, 'Dolce&Gabbana': 32, 'SECERTMU': 9, 'As Show': 10, 'Versace': 20, 'Paco Rabanne': 45, 'Grandeur': 1, 'Armaf': 34, 'Carolina Herrera': 15, 'Dolce & Gabbana': 10, 'Clinique': 2, 'Dumont': 1, 'Afnan': 13, 'Azzaro': 15, "Penhaligon's": 4, 'Bharara': 3, 'Valentino': 10, 'Guy Laroche': 5, 'Montblanc': 6, 'Rasasi': 9, 'Calvin Klein': 17, 'UOMO': 1, 'Givenchy': 9, 'Polo Ralph Lauren': 13, 'C.K': 1, 'John Varvatos': 4, 'Nautica': 4, 'As Picture Show': 2, 'Kenneth Cole': 7, 'Tommy Hilfiger': 4, '2nd To None': 1, 'Yves Saint Laurent': 30, 'Cologne': 16, 'AS SHOWN': 6, 'Roja': 4, 'MetaHerbal Labs': 1, 'Mirage Brands': 2, 'Abercrombie & Fitch': 13, 'Moschino': 5, 'As Shown': 2, '~ DOLCE & GABBANA ~': 1, 'As picture show': 1, 'Superz Budapest': 1, 'Gianni Versace': 2, 'Christian Dior': 2, 'HERMÈS': 9, 'Diesel': 5, 'Lacoste': 5, 'Dossier': 8, 'Burberry': 12, 'Michael Malul': 1, 'Zara': 4, 'Aramis': 2, 'Jean Paul Gaultier': 13, 'Davidoff': 7, 'As Picture Shown': 1, 'Bvlgari': 8, 'Parfums de Marly': 9, 'Salvatore Ferragamo': 8, 'MontBlanc': 2, 'Ard Al Zaafaran': 1, 'Karl Lagerfeld': 2, 'J. Del Pozo': 4, 'Sean John': 2, 'AS PICTURE SHOWN': 1, 'YSL': 4, 'Jaguar': 4, 'EBC': 1, 'Bath & Body Works': 6, 'Issey Miyake': 3, 'King': 1, 'Prada': 2, 'HUGO BOSS': 5, 'Mont Blanc': 4, 'BHARARA': 2, 'Tommy Bahama': 4, 'Paul Sebastian': 2, 'Halloween': 1, 'Boucheron': 2, 'Thierry Mugler': 1, 'Jo Malone': 1, 'ISSEY MIYAKE': 2, 'Khadlaj': 1, 'Louis Vuitton': 3, 'Creed': 12, 'MFK': 1, 'Hermes': 3, 'fragrance': 1, 'CHANEL': 7, 'Lalique': 6, 'Liz Claiborne': 7, 'By Al Hambra': 2, 'Joop': 2, 'As shown': 2, 'Ted Lapidus': 1, 'AXE': 2, 'as showed': 3, 'Lomani': 2, 'king of kings': 1, 'rue21': 1, 'Roja Dove': 1, 'Tom Ford': 4, 'Al Wataniah': 2, 'MACARENA': 1, 'Bentley': 4, 'Coach': 5, 'Coty': 2, 'Lanvin': 1, 'Claude Marsal': 1, 'NIKOS': 1, 'Lucianno': 1, 'Viktor & Rolf': 6, 'Rochas': 1, 'PRADA': 11, 'Classic Brands': 1, 'REYANE TRADITION': 1, 'Giorgio Beverly Hills': 1, 'Myrurgia': 2, 'Jovan': 1, 'Coty Inc.': 1, 'MONT BLANC LEGEND': 1, 'KING OF KINGS': 1, 'Ulric de Varens': 1, 'Emporio Armani': 5, 'Maison Francis Kurkdjian': 2, 'Fragrance World': 2, 'Allsaints': 1, 'Avon': 5, 'Yves de Sistelle': 2, 'Chanel': 1, 'Limited Edition': 1, 'Kenneth Cole Reaction': 1, 'Bond No. 9': 3, 'Acqua di Parma': 2, 'AS PHOTOS': 1, 'GUERLAIN PARIS': 1, 'Al Haramain': 3, 'Roja Parfums': 1, 'Narciso Rodriguez': 1, 'Topshelf': 1, 'Brut': 1, 'Ed Hardy': 2, 'Hollister': 4, 'FM': 1, 'Paris Hilton': 1, 'Heaven Scents': 1, 'Milestone Perfumes': 2, 'KENZO': 2, 'Mercedes-Benz': 4, 'Franck Olivier': 3, 'Missoni': 1, 'Halston': 1, nan: 1, 'Baron': 1, 'adidas': 1, 'Guerlain': 3, 'Branded': 1, 'Acqua Di Gio': 1, 'Reyane Tradition': 2, 'Old Spice': 1, 'Lauren Ralph Lauren': 1, 'Clive Christian': 1, 'GIORGIO ARM.ANI': 1, 'Victor & Rolf': 1, 'Polo': 1, 'Roberto Cavalli': 1, 'Emanuelle Ungaro': 1, 'CURVE': 1, 'Michael Malul London': 2, 'Estée Lauder': 1, 'Pierre Cardin': 2, 'RawChemistry': 1, 'Sterling': 2, 'Territoire': 1, 'Jimmy Choo': 5, 'Lapidus': 2, 'Mary Kay': 1, 'L’OCCITANE': 1, 'Have A Scent': 1, 'Fragrance Couture': 1, 'Mancera': 2, 'Hugo Boss': 2, 'LLURE SX': 1, 'Jacques Bogart': 1, 'FC': 1, 'Pheromones': 1, 'Cartier': 2, 'Assorted': 2, 'HINODE': 1, 'Michael Jordan': 2, 'ysl': 1, 'Designer Series': 1, 'Alexandria Fragrances': 1, 'Maison Martin Margiela': 1, 'El Ganso': 1, 'VICTOR MANUELLE': 1, 'English Laundry': 1, 'Luxury': 1, 'Jil Sander': 1, 'MAISON ALHAMBRA': 1, 'Hybrid & Company': 1, 'Perry Ellis': 4, 'Houbigant': 1, 'GIVENCHY': 2, 'Does not apply': 1, 'Tiffany': 1, 'emper': 1, 'MONTALE': 1, 'BRUT': 2, 'CHRISTIAN DIOR': 1, 'Blue Perfumes': 1, 'fragance one': 1, 'Elixir': 1, 'Michael Malul Gents Scents': 1, 'Xerjoff': 2, 'united scents': 1, 'aladdin': 1, 'Hanae Mori': 1, 'Phillips-Van Heusen': 1, 'Elizabeth Taylor': 1, 'Al Rehab': 1, 'BOD man': 1, 'Amouage': 1, 'Dana': 1, 'Dvyne Fragrances': 1, 'Arabian Oud': 1, 'David Beckham': 1, 'Falic Fashion Group': 1, 'Michel Germain': 1, 'The Baron': 1, 'Nina Ricci': 1, 'Vince Camuto': 1, 'Maison Margiela': 1, 'Mercedes Benz': 1, 'Juicy Couture': 1, 'Cuba': 1, 'Mandarin Duck': 1, 'GUESS': 1, 'Estee Lauder': 1}
20